### ISSUE TITLE
error occurs

### ISSUE THREAD

**Issue by zhxiaom5** [criteo/mewpoke#43]
> Configure project :
Evaluating root project 'mewpoke' using build file '/tmp/mewpoke/build.gradle'.
Building version: 1.0.2-49-g2456894
All projects evaluated.
Selected primary task 'build' from project :

FAILURE: Build failed with an exception.

* What went wrong:
Method com/github/jengelman/gradle/plugins/shadow/internal/DependencyFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

**Comment by erebe** [comment]
Thanks for reporting
Here this fix https://github.com/criteo/mewpoke/commit/d6487ca9bebefdb7ffa1d9e1592b8125ad7ac3d2
